name: Android CI - Build Debug APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Install Android SDK & NDK (via sdkmanager)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          ndk: '21.4.7075529'
          # This action requires a "script" input. Keep it minimal when only installing SDK/NDK.
          script: echo "android sdk & ndk installed"

      - name: Grant execute to Gradlew (module wrapper)
        # The Android module is in android-app/, so make sure the wrapper there is runnable.
        run: chmod +x ./android-app/gradlew

      - name: Build debug APK
        run: ./gradlew :app:assembleDebug --no-daemon
        working-directory: android-app

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android-app/app/build/outputs/apk/debug/app-debug.apk
