name: Build APK (adapted - android-app wrapper)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', 'android-app/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Ensure android-app gradle wrapper exists
        run: |
          if [ -f ./android-app/gradlew ]; then
            echo "android-app/gradlew: present"
          else
            echo "android-app/gradlew: MISSING - upload gradlew + gradle/wrapper/* into android-app/" >&2
            ls -la android-app || true
            exit 1
          fi

      - name: Make android-app gradlew executable
        run: chmod +x ./android-app/gradlew

      - name: Install Android command line tools + SDK components (robust)
        run: |
          set -euo pipefail
          SDKROOT="${ANDROID_SDK_ROOT}"
          echo "Installing Android SDK to ${SDKROOT}"
          mkdir -p "${SDKROOT}"

          cd "${RUNNER_TEMP}"
          ZIP="commandlinetools-linux.zip"
          echo "Downloading commandline tools..."
          curl -fsSL "https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip" -o "$ZIP"

          mkdir -p "${SDKROOT}/cmdline-tools/tmp"
          unzip -q "$ZIP" -d "${SDKROOT}/cmdline-tools/tmp"
          mkdir -p "${SDKROOT}/cmdline-tools/latest"
          mv "${SDKROOT}/cmdline-tools/tmp/"* "${SDKROOT}/cmdline-tools/latest/" || true
          rm -rf "${SDKROOT}/cmdline-tools/tmp"
          rm -f "$ZIP"

          SDKMANAGER_CMD="${SDKROOT}/cmdline-tools/latest/bin/sdkmanager"
          chmod +x "${SDKMANAGER_CMD}"

          export ANDROID_HOME="${SDKROOT}"
          export ANDROID_SDK_ROOT="${SDKROOT}"

          yes | "${SDKMANAGER_CMD}" --sdk_root="${SDKROOT}" "platform-tools" "platforms;android-33" "build-tools;33.0.2" "cmake;3.22.1" "ndk;21.4.7075529" || true
          yes | "${SDKMANAGER_CMD}" --sdk_root="${SDKROOT}" --licenses || true

          echo "ANDROID_HOME=${SDKROOT}" >> "${GITHUB_ENV}"
          echo "ANDROID_SDK_ROOT=${SDKROOT}" >> "${GITHUB_ENV}"
          echo "${SDKROOT}/platform-tools" >> "${GITHUB_PATH}"
          echo "${SDKROOT}/build-tools/33.0.2" >> "${GITHUB_PATH}"

      
      - name: Print Java & Gradle versions (for logs)
        run: |
          java -version || true
          ./android-app/gradlew --version || true

      - name: Build APKs (debug + release) using android-app wrapper
        run: |
          set -euo pipefail
          echo "Running gradlew from android-app/"
          ./android-app/gradlew -p android-app assembleDebug assembleRelease --stacktrace --no-daemon
        env:
          JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF8"

      - name: Show APK outputs
        run: |
          echo "Debug APK:"
          ls -la android-app/app/build/outputs/apk/debug || true
          echo "Release APK:"
          ls -la android-app/app/build/outputs/apk/release || true

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-apks
          path: |
            android-app/app/build/outputs/apk/debug/*.apk
            android-app/app/build/outputs/apk/release/*.apk
